[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.9.0"
edition = { workspace = true }
repository = 'https://github.com/bytecodealliance/wit-bindgen'
license = "Apache-2.0 WITH LLVM-exception"
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
CLI tool to generate bindings for WIT documents and the component model.
"""

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wasi_snapshot_preview1",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.71"
bitflags = "2.3.3"
heck =  { version = "0.4", features = ["unicode"] }
pulldown-cmark = { version = "0.9", default-features = false }
clap = { version = "4.3.11", features = ["derive"] }
env_logger = "0.10.0"
indexmap = "2.0.0"

wasm-encoder = "0.31.0"
wasm-metadata = "0.10.0"
wat = "1.0.68"
wit-parser = "0.9.1"
wit-component = "0.13.0"

wit-bindgen-core = { path = 'crates/core', version = '0.9.0' }
wit-bindgen-c = { path = 'crates/c', version = '0.9.0' }
wit-bindgen-rust = { path = "crates/rust", version = "0.9.0" }
wit-bindgen-teavm-java = { path = 'crates/teavm-java', version = '0.9.0' }
wit-bindgen-go = { path = 'crates/go', version = '0.7.0' }
wit-bindgen-markdown = { path = 'crates/markdown', version = '0.9.0' }
wit-bindgen-js = { path = 'crates/js', version = '0.0.0' }
wit-bindgen-rust-lib = { path = 'crates/rust-lib', version = '0.9.0' }
wit-bindgen = { path = 'crates/guest-rust', version = '0.9.0', default-features = false }
wit-bindgen-rust-macro-shared = { path = 'crates/rust-macro-shared', version = '0.3.0' }

[[bin]]
name = "wit-bindgen"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-c = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-markdown = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-teavm-java = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-go = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-js = { workspace = true, features = ['clap'], optional = true }
wat = { workspace = true }
wit-component = { workspace = true }
wasm-encoder = { workspace = true }

[features]
default = [
  'c',
  'rust',
  'markdown',
  'teavm-java',
  'go',
  'js',
]
c = ['dep:wit-bindgen-c']
rust = ['dep:wit-bindgen-rust']
markdown = ['dep:wit-bindgen-markdown']
teavm-java = ['dep:wit-bindgen-teavm-java']
go = ['dep:wit-bindgen-go']
js = ['dep:wit-bindgen-js']

[dev-dependencies]
heck = { workspace = true }
wasmtime = { version = "11", features = ['component-model'] }
test-artifacts = { path = 'crates/test-rust-wasm/artifacts' }
wit-parser = { workspace = true }
